name: 'Apply Terraform'
description: 'Apply Terraform With State Saved in Google Cloud Storage'
inputs:
  tf_bucket:
    description: 'Terraform Bucket Name'
    required: true
  cosmos_name:
    description: 'Cosmos name'
    required: false
  realm_name:
    description: 'Realm name'
    required: true
  foundation_name:
    description: 'Foundation name'
    required: true
  app_name:
    description: 'Application name'
    required: true
    default: ''
  env_name:
    description: 'Environment Name'
    required: true
    default: 'base'

runs:
  using: 'composite'
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init Foundation
      if: ${{ inputs.app_name == '' }}
      shell: bash
      run: |
        terraform -chdir=iac/environments/${{ inputs.env_name }} init \
        -backend-config="bucket=${{ inputs.tf_bucket }}" \
        -backend-config="prefix=${{ inputs.realm_name }}/_/${{ inputs.foundation_name }}/_/terraform/state"

    - name: Terraform init Application
      if: ${{ inputs.app_name != '' }}
      shell: bash
      run: |
        terraform -chdir=iac/environments/${{ inputs.env_name }} init \
        -backend-config="bucket=${{ inputs.tf_bucket }}" \
        -backend-config="prefix=${{ inputs.realm_name }}/_/${{ inputs.foundation_name }}/${{ inputs.app_name }}/${{ inputs.env_name }}/terraform/state"

    - name: Terraform Apply Application
      if: ${{ inputs.app_name == '' }}
      shell: bash
      run: |
        terraform -chdir=iac/environments/${{ inputs.env_name }} apply -auto-approve

    - name: Terraform Apply Application
      if: ${{ inputs.app_name != '' }}
      shell: bash
      run: |
        terraform -chdir=iac/environments/${{ inputs.env_name }} apply -auto-approve
