name: 'Apply Terraform'
description: 'Apply Terraform With State Saved in Google Cloud Storage'
inputs:
  tf_bucket_name:
    description: 'Terraform Bucket Name'
    required: true
  cosmos_name:
    description: 'Cosmos name'
    required: false
  realm_name:
    description: 'Realm name'
    required: true
    default: ''
  foundation_name:
    description: 'Foundation name'
    required: true
    default: ''
  app_name:
    description: 'Application name'
    required: true
    default: ''
  env_name:
    description: 'Environment Name'
    required: true
    default: 'base'

runs:
  using: 'composite'
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init Foundation
      if: ${{ inputs.app_name == '' }}
      shell: bash
      run: |
        if [ -z "${{ inputs.foundation_name }}" ]; then
          PREFIX="_/terraform/state"
        elif [ -z "${{ inputs.app_name }}" ]; then
          PREFIX="${{ inputs.realm_name }}/_/${{ inputs.foundation_name }}/_/terraform/state"
        else
          PREFIX="${{ inputs.realm_name }}/_/${{ inputs.foundation_name }}/${{ inputs.app_name }}/${{ inputs.env_name }}/terraform/state"
        fi
        
        terraform -chdir=iac/environments/${{ inputs.env_name }} init \
        -backend-config="bucket=${{ inputs.tf_bucket_name }}" \
        -backend-config="prefix=$PREFIX"

    - name: Terraform Apply Application
      shell: bash
      run: |
        terraform -chdir=iac/environments/${{ inputs.env_name }} apply -auto-approve
